### ISSUE TITLE
As a designer I would like to know if patient details view is ever used

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-analytics#2]
To inform where the best place to put fields is.

**Comment by GabPoll** [comment]
i.e. order the fields in patient details view so most frequently accessed are nearer the top

**Comment by davidmiller** [comment]
So, I think it's impossible to do #3 without also having this data in place !

I'm going to close this as  a duplicate...

**Comment by GabPoll** [comment]
agree
